### ISSUE TITLE
Unable to run madspam.py

### ISSUE THREAD

**Issue by FarenFast** [mrmadbhai/MadSpam#1]
~/Developer/MadSpam $ python madspam.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Developer/MadSpam/madspam.py", line 1, in <module>
    import pyautogui as madbhai
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pyautogui/__init__.py", line 249, in <module>
    import mouseinfo
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mouseinfo/__init__.py", line 223, in <module>
    _display = Display(os.environ['DISPLAY'])
                       ~~~~~~~~~~^^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'DISPLAY'

Can u solve this error?

**Comment by mrmadbhai** [comment]
This tool is not available on Termux
